_wandb:
    value:
        cli_version: 0.25.1
        e:
            c5z4sftahhmq8zj3qvc8bj2s0z2zv1v1:
                codePath: experiments/phase2_PEFT/train_gpt_peft.py
                codePathLocal: experiments/phase2_PEFT/train_gpt_peft.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "144942542848"
                        used: "119465152512"
                email: anthonnyolime@gmail.com
                executable: /opt/pg-venv/bin/python3
                git:
                    commit: f5b2ff8a4b227090e3cc1b2900a66489d3106dc2
                    remote: git@github.com:aviv-anthonnyolime/parameter-golf.git
                gpu: NVIDIA A10G
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-af022ed0-530e-05cb-0b13-570e82709889
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-115799ce-608d-30ae-ab7b-dffcdb13a32c
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-a4d45d56-8892-e8b4-dc1a-54f339d9104b
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-5de20318-4584-6c0c-d7c9-bf32dd35b212
                host: ip-172-16-41-240.eu-west-1.compute.internal
                memory:
                    total: "200485216256"
                os: Linux-5.10.251-248.983.amzn2.x86_64-x86_64-with-glibc2.26
                program: /home/ec2-user/SageMaker/parameter-golf/experiments/phase2_PEFT/train_gpt_peft.py
                python: CPython 3.12.12
                root: /home/ec2-user/SageMaker/parameter-golf
                startedAt: "2026-03-24T20:36:14.120240Z"
                writerId: c5z4sftahhmq8zj3qvc8bj2s0z2zv1v1
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
                - 62
            "4": 3.12.12
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
adam_eps:
    value: 1e-08
adapter_alpha:
    value: 64
adapter_location:
    value: all
adapter_method:
    value: noble
adapter_noble_lr:
    value: 0.001
adapter_rank:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.95
data_path:
    value: ./data/datasets/fineweb10B_sp1024
embed_lr:
    value: 0.6
grad_accum_steps_override:
    value: 2
grad_clip_norm:
    value: 0.3
head_lr:
    value: 0.008
init_strategy:
    value: zeros
iterations:
    value: 20000
logit_softcap:
    value: 30
matrix_lr:
    value: 0.025
max_wallclock_seconds:
    value: 1200
mlp_mult:
    value: 2
model_dim:
    value: 768
muon_backend_steps:
    value: 5
muon_momentum:
    value: 0.99
muon_momentum_warmup_start:
    value: 0.92
muon_momentum_warmup_steps:
    value: 1500
num_heads:
    value: 8
num_kv_heads:
    value: 4
num_layers:
    value: 10
num_unique_layers:
    value: 5
qk_gain_init:
    value: 1.5
rope_base:
    value: 10000
run_id:
    value: peft_noble_r64_all_5U_768D
scalar_lr:
    value: 0.025
seed:
    value: 1337
skip_ttt:
    value: 1
tie_embeddings:
    value: true
tied_embed_init_std:
    value: 0.005
tied_embed_lr:
    value: 0.035
tokenizer_path:
    value: ./data/tokenizers/fineweb_1024_bpe.model
train_batch_tokens:
    value: 524288
train_files:
    value: ./data/datasets/fineweb10B_sp1024/fineweb_train_*.bin
train_log_every:
    value: 10
train_seq_len:
    value: 1024
ttt_batch_size:
    value: 64
ttt_chunk_size:
    value: 256
ttt_eval_seq_len:
    value: 1024
ttt_lora_lr:
    value: 0.01
ttt_lora_rank:
    value: 8
val_batch_size:
    value: 524288
val_files:
    value: ./data/datasets/fineweb10B_sp1024/fineweb_val_*.bin
val_loss_every:
    value: 1000
vocab_size:
    value: 1024
wandb_api_key:
    value: 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
wandb_enabled:
    value: true
wandb_entity:
    value: citaman
wandb_project:
    value: Openai-challenge-parameter-golf
warmdown_iters:
    value: 400
warmup_steps:
    value: 20
